name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose with Unit Tests
      run: |
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }} 
        docker-compose run web python3 manage.py test

