name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        docker-compose up
